# Generated by Django 5.1.7 on 2025-03-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCmmsportals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceReport',
        ),
        migrations.DeleteModel(
            name='ReportAttachment',
        ),
    ]
