"""add_production_models

Revision ID: 98cd38dd7d80
Revises: 1cc1a43cd083
Create Date: 2026-08-02 17:15:17.550987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '98cd38dd7d80'
down_revision: Union[str, None] = '1cc1a43cd083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_code'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_maintenance_reports_id'), table_name='maintenance_reports')
    op.drop_index(op.f('ix_maintenance_reports_report_number'), table_name='maintenance_reports')
    op.drop_table('maintenance_reports')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('craftsman_skills')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_packaging_orders_id'), table_name='packaging_orders')
    op.drop_index(op.f('ix_packaging_orders_order_number'), table_name='packaging_orders')
    op.drop_table('packaging_orders')
    op.drop_table('equipment_operators')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_craftsmen_id'), table_name='craftsmen')
    op.drop_table('craftsmen')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_work_order_number'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_production_lines_id'), table_name='production_lines')
    op.drop_index(op.f('ix_production_lines_line_code'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_equipment_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('equipment_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('purchase_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('warranty_expiry', sa.VARCHAR(length=20), nullable=True),
    sa.Column('specifications', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_equipment_id'), 'equipment', ['equipment_id'], unique=1)
    op.create_table('skills',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('production_lines',
    sa.Column('line_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('capacity_per_hour', sa.FLOAT(), nullable=True),
    sa.Column('capacity_unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('equipment_config', sqlite.JSON(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('floor', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lines_line_code'), 'production_lines', ['line_code'], unique=1)
    op.create_index(op.f('ix_production_lines_id'), 'production_lines', ['id'], unique=False)
    op.create_table('work_orders',
    sa.Column('work_order_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('work_order_type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=6), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('scheduled_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('due_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('started_at', sa.VARCHAR(length=30), nullable=True),
    sa.Column('completed_at', sa.VARCHAR(length=30), nullable=True),
    sa.Column('estimated_hours', sa.INTEGER(), nullable=True),
    sa.Column('actual_hours', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('completion_notes', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['craftsmen.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_work_order_number'), 'work_orders', ['work_order_number'], unique=1)
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_table('facilities',
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('facility_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('facility_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('gps_coordinates', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('manager_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('manager_contact', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_code')
    )
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_table('craftsmen',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('position', sa.VARCHAR(length=100), nullable=True),
    sa.Column('hire_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('certification_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('hourly_rate', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_craftsmen_id'), 'craftsmen', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('facility_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('department_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('manager_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cost_center', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_code')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('shifts',
    sa.Column('production_line_id', sa.INTEGER(), nullable=False),
    sa.Column('shift_type', sa.VARCHAR(length=9), nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=10), nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=10), nullable=False),
    sa.Column('team_leader_id', sa.INTEGER(), nullable=True),
    sa.Column('operators', sqlite.JSON(), nullable=True),
    sa.Column('active_days', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['team_leader_id'], ['craftsmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_table('equipment_operators',
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('craftsman_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['craftsman_id'], ['craftsmen.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('equipment_id', 'craftsman_id')
    )
    op.create_table('packaging_orders',
    sa.Column('order_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('production_order_id', sa.INTEGER(), nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('product_code', sa.VARCHAR(length=100), nullable=True),
    sa.Column('target_quantity', sa.FLOAT(), nullable=False),
    sa.Column('packaged_quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=False),
    sa.Column('packaging_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('packaging_material', sa.VARCHAR(length=200), nullable=True),
    sa.Column('units_per_package', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('scheduled_start', sa.VARCHAR(length=30), nullable=True),
    sa.Column('scheduled_end', sa.VARCHAR(length=30), nullable=True),
    sa.Column('actual_start', sa.VARCHAR(length=30), nullable=True),
    sa.Column('actual_end', sa.VARCHAR(length=30), nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['craftsmen.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_orders_order_number'), 'packaging_orders', ['order_number'], unique=1)
    op.create_index(op.f('ix_packaging_orders_id'), 'packaging_orders', ['id'], unique=False)
    op.create_table('production_orders',
    sa.Column('order_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('production_line_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('product_code', sa.VARCHAR(length=100), nullable=True),
    sa.Column('target_quantity', sa.FLOAT(), nullable=False),
    sa.Column('produced_quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=False),
    sa.Column('defect_quantity', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('scheduled_start', sa.VARCHAR(length=30), nullable=True),
    sa.Column('scheduled_end', sa.VARCHAR(length=30), nullable=True),
    sa.Column('actual_start', sa.VARCHAR(length=30), nullable=True),
    sa.Column('actual_end', sa.VARCHAR(length=30), nullable=True),
    sa.Column('shift_id', sa.INTEGER(), nullable=True),
    sa.Column('supervisor_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('completion_notes', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=1)
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.create_table('craftsman_skills',
    sa.Column('craftsman_id', sa.INTEGER(), nullable=False),
    sa.Column('skill_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['craftsman_id'], ['craftsmen.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('craftsman_id', 'skill_id')
    )
    op.create_table('companies',
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('industry_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('registration_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('website', sa.VARCHAR(length=200), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=50), nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), nullable=False),
    sa.Column('working_hours_start', sa.VARCHAR(length=10), nullable=True),
    sa.Column('working_hours_end', sa.VARCHAR(length=10), nullable=True),
    sa.Column('working_days', sa.VARCHAR(length=50), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit_cost', sa.FLOAT(), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('performed_by', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('maintenance_reports',
    sa.Column('work_order_id', sa.INTEGER(), nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('craftsman_id', sa.INTEGER(), nullable=False),
    sa.Column('report_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('work_performed', sa.TEXT(), nullable=False),
    sa.Column('findings', sa.TEXT(), nullable=True),
    sa.Column('recommendations', sa.TEXT(), nullable=True),
    sa.Column('parts_used', sa.TEXT(), nullable=True),
    sa.Column('labor_hours', sa.INTEGER(), nullable=True),
    sa.Column('equipment_operational', sa.BOOLEAN(), nullable=False),
    sa.Column('follow_up_required', sa.BOOLEAN(), nullable=False),
    sa.Column('attachments', sa.TEXT(), nullable=True),
    sa.Column('completed_at', sa.VARCHAR(length=30), nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=True),
    sa.Column('reviewed_at', sa.VARCHAR(length=30), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['craftsman_id'], ['craftsmen.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_reports_report_number'), 'maintenance_reports', ['report_number'], unique=1)
    op.create_index(op.f('ix_maintenance_reports_id'), 'maintenance_reports', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('item_code', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=13), nullable=False),
    sa.Column('unit_of_measure', sa.VARCHAR(length=20), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('min_quantity', sa.FLOAT(), nullable=True),
    sa.Column('max_quantity', sa.FLOAT(), nullable=True),
    sa.Column('reorder_point', sa.FLOAT(), nullable=True),
    sa.Column('unit_cost', sa.FLOAT(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('supplier', sa.VARCHAR(length=200), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('batch_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('expiry_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_item_code'), 'inventory_items', ['item_code'], unique=1)
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    # ### end Alembic commands ###
