"""initial baseline

Revision ID: eb1eee384a95
Revises: 
Create Date: 2026-08-05 23:05:29.196062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1eee384a95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('industry_type', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('working_hours_start', sa.String(length=10), nullable=True),
    sa.Column('working_hours_end', sa.String(length=10), nullable=True),
    sa.Column('working_days', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('equipment',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('equipment_id', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('OPERATIONAL', 'MAINTENANCE', 'BREAKDOWN', 'RETIRED', name='equipmentstatus'), nullable=False),
    sa.Column('purchase_date', sa.String(length=20), nullable=True),
    sa.Column('warranty_expiry', sa.String(length=20), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_id'), 'equipment', ['equipment_id'], unique=True)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_table('inventory_categories',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_categories_id'), 'inventory_categories', ['id'], unique=False)
    op.create_table('production_lines',
    sa.Column('line_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'IDLE', 'MAINTENANCE', 'OFFLINE', name='productionlinestatus'), nullable=False),
    sa.Column('capacity_per_hour', sa.Float(), nullable=True),
    sa.Column('capacity_unit', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lines_id'), 'production_lines', ['id'], unique=False)
    op.create_index(op.f('ix_production_lines_line_code'), 'production_lines', ['line_code'], unique=True)
    op.create_table('quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_inspections', sa.Integer(), nullable=True),
    sa.Column('passed_inspections', sa.Integer(), nullable=True),
    sa.Column('failed_inspections', sa.Integer(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('total_ncrs', sa.Integer(), nullable=True),
    sa.Column('open_ncrs', sa.Integer(), nullable=True),
    sa.Column('closed_ncrs', sa.Integer(), nullable=True),
    sa.Column('defect_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_metrics_id'), 'quality_metrics', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('permissions_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'CRAFTSMAN', 'INVENTORY', 'QUALITY', 'PRODUCTION', 'READONLY', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('craftsmen',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.String(length=20), nullable=True),
    sa.Column('certification_level', sa.String(length=50), nullable=True),
    sa.Column('hourly_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_craftsmen_id'), 'craftsmen', ['id'], unique=False)
    op.create_table('facilities',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('facility_code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('gps_coordinates', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('manager_contact', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_code')
    )
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('min_quantity', sa.Float(), nullable=True),
    sa.Column('max_quantity', sa.Float(), nullable=True),
    sa.Column('reorder_point', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_code'), 'inventory_items', ['item_code'], unique=True)
    op.create_table('production_line_equipment',
    sa.Column('production_line_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=True),
    sa.Column('operators', sa.JSON(), nullable=True),
    sa.Column('cycle_time_minutes', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_line_equipment_id'), 'production_line_equipment', ['id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'CANCELLED', name='salesorderstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='salesorderpriority'), nullable=False),
    sa.Column('order_date', sa.String(length=20), nullable=True),
    sa.Column('requested_delivery_date', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_by', sa.Integer(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_created_by'), 'sales_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_sales_orders_customer_id'), 'sales_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_id'), 'sales_orders', ['id'], unique=False)
    op.create_index(op.f('ix_sales_orders_order_number'), 'sales_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_sales_orders_status'), 'sales_orders', ['status'], unique=False)
    op.create_table('craftsman_skills',
    sa.Column('craftsman_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['craftsman_id'], ['craftsmen.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('craftsman_id', 'skill_id')
    )
    op.create_table('departments',
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('cost_center', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_code')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('equipment_operators',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('craftsman_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['craftsman_id'], ['craftsmen.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('equipment_id', 'craftsman_id')
    )
    op.create_table('inventory_transactions',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('RECEIPT', 'ISSUE', 'TRANSFER', 'ADJUSTMENT', 'RETURN', 'SCRAP', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('maintenance_catalogue_items',
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('compatible_equipment', sa.Text(), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_catalogue_items_id'), 'maintenance_catalogue_items', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_catalogue_items_item_code'), 'maintenance_catalogue_items', ['item_code'], unique=True)
    op.create_index(op.f('ix_maintenance_catalogue_items_item_type'), 'maintenance_catalogue_items', ['item_type'], unique=False)
    op.create_table('sales_order_items',
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('ordered_quantity', sa.Float(), nullable=False),
    sa.Column('fulfilled_quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_FULFILLED', 'FULFILLED', 'CANCELLED', name='salesorderlinestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_items_id'), 'sales_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_sales_order_items_item_id'), 'sales_order_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_sales_order_items_sales_order_id'), 'sales_order_items', ['sales_order_id'], unique=False)
    op.create_table('shifts',
    sa.Column('production_line_id', sa.Integer(), nullable=False),
    sa.Column('shift_type', sa.Enum('MORNING', 'AFTERNOON', 'NIGHT', 'ROTATING', name='shifttype'), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('team_leader_id', sa.Integer(), nullable=True),
    sa.Column('operators', sa.JSON(), nullable=True),
    sa.Column('active_days', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['team_leader_id'], ['craftsmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_table('work_orders',
    sa.Column('work_order_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_order_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'PREDICTIVE', 'EMERGENCY', 'MODIFICATION', 'INSPECTION', name='workordertype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='workorderpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='workorderstatus'), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.String(length=30), nullable=True),
    sa.Column('completed_at', sa.String(length=30), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('actual_hours', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['craftsmen.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_work_order_number'), 'work_orders', ['work_order_number'], unique=True)
    op.create_table('maintenance_reports',
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('craftsman_id', sa.Integer(), nullable=False),
    sa.Column('report_number', sa.String(length=100), nullable=False),
    sa.Column('work_performed', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('labor_hours', sa.Integer(), nullable=True),
    sa.Column('equipment_operational', sa.Boolean(), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.String(length=30), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['craftsman_id'], ['craftsmen.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_reports_id'), 'maintenance_reports', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_reports_report_number'), 'maintenance_reports', ['report_number'], unique=True)
    op.create_table('production_orders',
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('production_line_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('target_quantity', sa.Float(), nullable=False),
    sa.Column('produced_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('defect_quantity', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'CANCELLED', name='productionorderstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.String(length=30), nullable=True),
    sa.Column('scheduled_end', sa.String(length=30), nullable=True),
    sa.Column('actual_start', sa.String(length=30), nullable=True),
    sa.Column('actual_end', sa.String(length=30), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=True)
    op.create_table('inventory_requisitions',
    sa.Column('requisition_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'CANCELLED', name='requisitionstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='requisitionpriority'), nullable=False),
    sa.Column('needed_by', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_by', sa.Integer(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_requisitions_id'), 'inventory_requisitions', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_requisitions_requested_by'), 'inventory_requisitions', ['requested_by'], unique=False)
    op.create_index(op.f('ix_inventory_requisitions_requisition_number'), 'inventory_requisitions', ['requisition_number'], unique=True)
    op.create_index(op.f('ix_inventory_requisitions_status'), 'inventory_requisitions', ['status'], unique=False)
    op.create_table('packaging_orders',
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('target_quantity', sa.Float(), nullable=False),
    sa.Column('packaged_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('packaging_type', sa.String(length=100), nullable=True),
    sa.Column('packaging_material', sa.String(length=200), nullable=True),
    sa.Column('units_per_package', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'CANCELLED', name='productionorderstatus'), nullable=False),
    sa.Column('scheduled_start', sa.String(length=30), nullable=True),
    sa.Column('scheduled_end', sa.String(length=30), nullable=True),
    sa.Column('actual_start', sa.String(length=30), nullable=True),
    sa.Column('actual_end', sa.String(length=30), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['craftsmen.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_orders_id'), 'packaging_orders', ['id'], unique=False)
    op.create_index(op.f('ix_packaging_orders_order_number'), 'packaging_orders', ['order_number'], unique=True)
    op.create_table('quality_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_number', sa.String(length=50), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('inspection_type', sa.String(length=100), nullable=False),
    sa.Column('inspection_date', sa.DateTime(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('defects_found', sa.Integer(), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='inspectionstatus'), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'CONDITIONAL', 'PENDING', name='inspectionresult'), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_inspections_id'), 'quality_inspections', ['id'], unique=False)
    op.create_index(op.f('ix_quality_inspections_inspection_number'), 'quality_inspections', ['inspection_number'], unique=True)
    op.create_table('inventory_requisition_items',
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('requested_quantity', sa.Float(), nullable=False),
    sa.Column('approved_quantity', sa.Float(), nullable=True),
    sa.Column('fulfilled_quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'REJECTED', 'CANCELLED', name='requisitionlinestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['inventory_requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_requisition_items_id'), 'inventory_requisition_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_requisition_items_item_id'), 'inventory_requisition_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_requisition_items_requisition_id'), 'inventory_requisition_items', ['requisition_id'], unique=False)
    op.create_table('non_conformance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ncr_number', sa.String(length=50), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', name='ncrseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'CORRECTIVE_ACTION', 'CLOSED', 'REJECTED', name='ncrstatus'), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('preventive_action', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['quality_inspections.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_non_conformance_reports_id'), 'non_conformance_reports', ['id'], unique=False)
    op.create_index(op.f('ix_non_conformance_reports_ncr_number'), 'non_conformance_reports', ['ncr_number'], unique=True)
    op.create_table('quality_inspection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_name', sa.String(length=200), nullable=False),
    sa.Column('specification', sa.String(length=500), nullable=True),
    sa.Column('measured_value', sa.String(length=200), nullable=True),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'CONDITIONAL', 'PENDING', name='inspectionresult'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['quality_inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_inspection_items_id'), 'quality_inspection_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_inspection_items_id'), table_name='quality_inspection_items')
    op.drop_table('quality_inspection_items')
    op.drop_index(op.f('ix_non_conformance_reports_ncr_number'), table_name='non_conformance_reports')
    op.drop_index(op.f('ix_non_conformance_reports_id'), table_name='non_conformance_reports')
    op.drop_table('non_conformance_reports')
    op.drop_index(op.f('ix_inventory_requisition_items_requisition_id'), table_name='inventory_requisition_items')
    op.drop_index(op.f('ix_inventory_requisition_items_item_id'), table_name='inventory_requisition_items')
    op.drop_index(op.f('ix_inventory_requisition_items_id'), table_name='inventory_requisition_items')
    op.drop_table('inventory_requisition_items')
    op.drop_index(op.f('ix_quality_inspections_inspection_number'), table_name='quality_inspections')
    op.drop_index(op.f('ix_quality_inspections_id'), table_name='quality_inspections')
    op.drop_table('quality_inspections')
    op.drop_index(op.f('ix_packaging_orders_order_number'), table_name='packaging_orders')
    op.drop_index(op.f('ix_packaging_orders_id'), table_name='packaging_orders')
    op.drop_table('packaging_orders')
    op.drop_index(op.f('ix_inventory_requisitions_status'), table_name='inventory_requisitions')
    op.drop_index(op.f('ix_inventory_requisitions_requisition_number'), table_name='inventory_requisitions')
    op.drop_index(op.f('ix_inventory_requisitions_requested_by'), table_name='inventory_requisitions')
    op.drop_index(op.f('ix_inventory_requisitions_id'), table_name='inventory_requisitions')
    op.drop_table('inventory_requisitions')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_maintenance_reports_report_number'), table_name='maintenance_reports')
    op.drop_index(op.f('ix_maintenance_reports_id'), table_name='maintenance_reports')
    op.drop_table('maintenance_reports')
    op.drop_index(op.f('ix_work_orders_work_order_number'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_sales_order_items_sales_order_id'), table_name='sales_order_items')
    op.drop_index(op.f('ix_sales_order_items_item_id'), table_name='sales_order_items')
    op.drop_index(op.f('ix_sales_order_items_id'), table_name='sales_order_items')
    op.drop_table('sales_order_items')
    op.drop_index(op.f('ix_maintenance_catalogue_items_item_type'), table_name='maintenance_catalogue_items')
    op.drop_index(op.f('ix_maintenance_catalogue_items_item_code'), table_name='maintenance_catalogue_items')
    op.drop_index(op.f('ix_maintenance_catalogue_items_id'), table_name='maintenance_catalogue_items')
    op.drop_table('maintenance_catalogue_items')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_table('equipment_operators')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('craftsman_skills')
    op.drop_index(op.f('ix_sales_orders_status'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_number'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_customer_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_created_by'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_production_line_equipment_id'), table_name='production_line_equipment')
    op.drop_table('production_line_equipment')
    op.drop_index(op.f('ix_inventory_items_item_code'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_craftsmen_id'), table_name='craftsmen')
    op.drop_table('craftsmen')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_quality_metrics_id'), table_name='quality_metrics')
    op.drop_table('quality_metrics')
    op.drop_index(op.f('ix_production_lines_line_code'), table_name='production_lines')
    op.drop_index(op.f('ix_production_lines_id'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_index(op.f('ix_inventory_categories_id'), table_name='inventory_categories')
    op.drop_table('inventory_categories')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
